export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const GET_AVAILABLE_USERS = 'GET_AVAILABLE_USERS';
export const SET_AVAILABLE_USERS = 'SET_AVAILABLE_USERS';

export const JOIN_CHATROOM = 'JOIN_CHATROOM';
export const LEAVE_CHATROOM = 'LEAVE_CHATROOM';
export const GET_CHATROOMS = 'GET_CHATROOMS';
export const SET_CHATROOMS = 'SET_CHATROOMS';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const REMOVE_MESSAGES = 'REMOVE_MESSAGES';

export const REFRESH_PAGE = 'REFRESH_PAGE';
